### ISSUE TITLE
Index Error in "LASSO_CD_mashiqi.m"

### ISSUE THREAD

**Issue by XuDafang** [mashiqi/lasso#1]
The original 150th - 152th codes,
`
%% trim the unused columns
betaTrace(:,(iter+1):end)	= [];
f(:,(iter+1):end)           = [];
`
should be
`%% trim the unused columns
betaTrace(:,iter:end)	= [];
f(:,iter:end)           = [];`

**Comment by mashiqi** [comment]
Could you please explain why we should also delete the 'iter'-th column? Thank you.

**Comment by mashiqi** [comment]
May I kindly ask what is the reason to delete the 'iter'-th column? Thank you.

**Comment by XuDafang** [comment]
> May I kindly ask what is the reason to delete the 'iter'-th column? Thank you.

This is because, in my application, the betaTrace(:, iter) is always a zero-vector. I don't know if it's the case for the other applications.

Please take a look at the following scenario. The condition `iter >= maxIter` in the 129th line of code is never met, thus the variable `FLAG` is always "True" and the 133rd line of code "iter = iter + 1" will always be executed in the loop. Be careful about this, before executing "iter = iter + 1", the betaTrace(:,iter) has been updated while betaTrace(:,iter + 1) is not. After the execution, betaTrace(:, iter) is not updated (a zero vector). If the `While FLAG` loop is broken because of the condition in the 137th line of code "isequal(fullSet,fullSet(activeSet))" being met, betaTrace(:, iter) is still a zero vector. Therefore, we should throw it away.
